/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  appDirectory: 'app',
  browserBuildDirectory: 'public/build',
  publicPath: '/build/',
  serverBuildDirectory: 'build',
  // TODO: when mui has esm support, remove this (default is esm)
  // check it https://github.com/mui/material-ui/issues/30671
  serverModuleFormat: 'cjs',
  serverDependenciesToBundle: [
    "@mui/material",
    "@mui/icons-material",
    "d3",
    "d3-axis",
    "d3-chord",
    "d3-color",
    "d3-interpolate",
    "d3-contour",
    "d3-delaunay",
    "d3-force",
    "d3-geo",
    "d3-hierarchy",
    "d3-path",
    "d3-polygon",
    "d3-quadtree",
    "d3-scale",
    "d3-scale-chromatic",
    "d3-selection",
    "d3-shape",
    "d3-ease",
    "d3-timer",
    "d3-transition",
    "d3-brush",
    "d3-dispatch",
    "d3-drag",
    "d3-zoom",
    "d3-array",
    "d3-dsv",
    "d3-fetch",
    "d3-format",
    "d3-random",
    "d3-time",
    "d3-time-format",
    "internmap",
  ]
};